services:
  - type: web
    name: my-telegram-bot
    env: python
    buildCommand: ""
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 7531144404:AAG047TB-zn1tCUMxZt8IPBSrZFfbDqsT0I
      - key: WEBHOOK_URL
        value: https://tt-doze-counter.onrender.com/webhook
    plan: free
