services:
  - type: web
    name: tt-doze-counter
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: 7531144404:AAG047TB-zn1tCUMxZt8IPBSrZFfbDqsT0I
